laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/', function () { return view('site.index'); });
Route::post('/', 'MailController@contacto');

Route::get('contacto', function () { return view('site.contacto'); })->name('contacto');
Route::post('contacto', 'MailController@contacto');

Route::get('nosotros', function () { return view('site.nosotros'); })->name('nosotros');

Route::group(['prefix' => 'blog'], function () {
    Route::get('/', 'PostController@index')->name('blog');
    Route::get('/{slug}', 'PostController@post')->name('blog.post');
});

Route::group(['prefix' => 'servicios'], function () {
    Route::get('/', 'ServicioController@index')->name('servicios');
    Route::get('prueba-exploratoria', 'ServicioController@prueba_exploratoria')->name('prueba.exploratoria');
    Route::get('prueba-de-permanencia-laboral', 'ServicioController@prueba_permanencia')->name('prueba.permanencia');
    Route::get('prueba-especifica', 'ServicioController@prueba_especifica')->name('prueba.especifica');
    Route::get('prueba-psicometrica', 'ServicioController@prueba_psicometrica')->name('prueba.psicometrica');
    Route::get('prueba-grafologica', 'ServicioController@prueba_grafologica')->name('prueba.grafologica');
    Route::get('prueba-eyedetect', 'ServicioController@prueba_eyedetect')->name('prueba.eyedetect');
    Route::get('estudio-socioeconomico', 'ServicioController@estudio_socioeconomico')->name('estudio.socioeconomico');
});

Route::group(['middleware' => 'auth', 'prefix' => 'dashboard'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::group(['namespace' => 'Dashboard'], function () {
        Route::resource('clientes', 'ClienteController', ['names' => ['index' => 'dashboard.clientes']]);
        Route::get('clientes/{id}/delete', 'ClienteController@destroy')->name('clientes.delete');
        
        Route::resource('reportes', 'ReporteController', ['names' => ['index' => 'dashboard.reportes']]);
        Route::get('reportes/{id}/delete', 'ReporteController@destroy')->name('reportes.delete');

        Route::resource('posts', 'PostController', ['names' => ['index' => 'dashboard.posts']]);
        Route::get('posts/{id}/publish', 'PostController@publish')->name('posts.publish');
        Route::get('posts/{id}/delete', 'PostController@destroy')->name('posts.delete');
    });
});

laravel/app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'clientes';

    protected $guarded = [];

    public function user() {
        return $this->belongsTo('App\User', 'user_id');
    }
}

laravel/app/Http/Controllers/Dashboard/ClienteController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Cliente;
use App\User;
use DB;

class ClienteController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = DB::table('clientes')
            ->join('users', 'clientes.user_id', '=', 'users.id')
            ->select('users.name', 'users.email', 'clientes.*')
            ->get();

        return view('dashboard.clientes.index')
            ->with('clientes', $clientes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Crear un ususario
        $user = new User;

        $user->name = $request->name;

        $user->email = $request->email;

        $user->password = bcrypt($request->password);

        $user->type = 'cliente';

        // Guardar datos
        $user->save();

        // Crear un cliente
        $cliente = new Cliente;

        $cliente->user_id = $user->id;

        $cliente->empresa = $request->empresa;

        $cliente->telefono = $request->telefono;

        $cliente->campo1 = $request->campo1;

        $cliente->campo2 = $request->campo2;

        $cliente->campo3 = $request->campo3;

        $cliente->campo4 = $request->campo4;

        $cliente->campo5 = $request->campo5;

        $cliente->campo6 = $request->campo6;

        $cliente->campo7 = $request->campo7;

        $cliente->campo8 = $request->campo8;

        $cliente->campo9 = $request->campo9;

        // Guardar datos
        $cliente->save();

        // Regreasar a la vista de clientes
        return redirect(route('dashboard.clientes'))
            ->with(['message' => 'Cliente guardado', 'class' => 'alert-info']);;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort('404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = DB::table('clientes')
            ->join('users', 'clientes.user_id', '=', 'users.id')
            ->select('users.name', 'users.email', 'clientes.*')
            ->where('clientes.id', $id)
            ->first();

        // return dd($cliente);
        return view('dashboard.clientes.edit')
            ->with('cliente', $cliente);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Obtener cliente
        $cliente = Cliente::find($id);

        $cliente->empresa = $request->empresa;

        $cliente->telefono = $request->telefono;

        $cliente->campo1 = $request->campo1;

        $cliente->campo2 = $request->campo2;

        $cliente->campo3 = $request->campo3;

        $cliente->campo4 = $request->campo4;

        $cliente->campo5 = $request->campo5;

        $cliente->campo6 = $request->campo6;

        $cliente->campo7 = $request->campo7;

        $cliente->campo8 = $request->campo8;

        $cliente->campo9 = $request->campo9;

        // Guardar datos
        $cliente->save();

        // Obtener ususario
        $user = User::where('id', $cliente->user_id)->first();

        $user->name = $request->name;

        $user->email = $request->email;

        // Guardar datos
        $user->save();

        //Regresar a la vista anterior
        return back()
            ->with(['message' => 'Cambios guardados', 'class' => 'alert-info']);;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user_id = Cliente::find($id)['user_id'];

        Cliente::destroy($id);

        User::destroy($user_id);

        return redirect(route('dashboard.clientes'))
            ->with(['message' => 'Cliente eliminado', 'class' => 'alert-info']);;
    }

}

laravel/app/Http/Controllers/Dashboard/PostController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Post;
use File;
class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post_list = Post::all();

        return view('dashboard.posts.index', compact('post_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->postFactory($request);

        return redirect()->route('dashboard.posts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('dashboard.posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->postFactory($request, $id);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        if ($post->image) {
            try{
                File::delete($post->image);
            }
            catch(\Exception $e){

            }
        }

        $post->delete();

        return back();
    }

    public function postFactory($request, $id = 0)
    {

        $post = Post::firstOrNew(['id' => $id]);

        $request['slug'] = str_slug($request->title);

        $this->postValidator($request, $post->id);

        $post->user_id = auth()->user()->id;
        $post->title = $request->title;
        $post->description = $request->description;
        $post->content = $request->content;

        if (!$id) {
            $post->slug = str_slug($request->title);
        }

        if ($request->image) {
            $image_name = pathinfo($request->image->getClientOriginalName(), PATHINFO_FILENAME);
            $image_ext = pathinfo($request->image->getClientOriginalName(), PATHINFO_EXTENSION);
            $image_fullname = date("Y_m_d_h_i_s_").str_slug($image_name, '_').'.'.$image_ext;

            $request->image->move('assets/uploads/posts', $image_fullname);

            if ($post->image) {
                try{
                    File::delete($post->image);
                }
                catch(\Exception $e){

                }
            }

            $post->image = 'assets/uploads/posts/'.$image_fullname;
        }

        $post->save();
    }

    public function postValidator($request, $id)
    {
        $this->validate($request, [
            'title' => "required|string|max:255|unique:posts,title,$id",
            'image' => 'image|max:5000',
            'description' => 'required|string',
            'content' => 'required|string',
            'slug' => "required|string|max:255|unique:posts,slug,$id",
        ]);
    }

    public function publish($id)
    {
        return back();
    }
}

laravel/app/Http/Controllers/Dashboard/ReporteController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Reporte;
use App\User;
use DB;

class ReporteController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reportes = DB::table('reportes')
            ->join('users', 'reportes.user_id', '=', 'users.id')
            ->join('clientes', 'users.id', '=', 'clientes.user_id')
            ->select('users.name', 'users.email', 'clientes.empresa', 'clientes.telefono', 'reportes.*')
            ->get();

        return view('dashboard.reportes.index')
            ->with('reportes', $reportes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::where('type', 'cliente')->get();

        return view('dashboard.reportes.create')
            ->with('usuarios', $users);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Crear un reporte
        $reporte = new Reporte;

        $reporte->user_id = $request->user_id;

        $reporte->campo1 = $request->campo1;

        $reporte->campo2 = $request->campo2;

        $reporte->campo3 = $request->campo3;

        $reporte->campo4 = $request->campo4;

        $reporte->campo5 = $request->campo5;

        $reporte->campo6 = $request->campo6;

        $reporte->campo7 = $request->campo7;

        $reporte->campo8 = $request->campo8;

        $reporte->campo9 = $request->campo9;

        // Guardar datos
        $reporte->save();

        return redirect(route('dashboard.reportes'))
            ->with(['message' => 'Reporte guardado', 'class' => 'alert-info']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort('404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reporte = Reporte::find($id);

        $users = User::where('type', 'cliente')->get();

        return view('dashboard.reportes.edit')
            ->with(['reporte' => $reporte, 'usuarios' => $users]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Obtener reporte
        $reporte = Reporte::find($id);

        $reporte->user_id = $request->user_id;

        $reporte->campo1 = $request->campo1;

        $reporte->campo2 = $request->campo2;

        $reporte->campo3 = $request->campo3;

        $reporte->campo4 = $request->campo4;

        $reporte->campo5 = $request->campo5;

        $reporte->campo6 = $request->campo6;

        $reporte->campo7 = $request->campo7;

        $reporte->campo8 = $request->campo8;

        $reporte->campo9 = $request->campo9;

        // Guardar datos
        $reporte->save();

        return back()
            ->with(['message' => 'Cambios guardados', 'class' => 'alert-info']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Reporte::destroy($id);
        return redirect(route('dashboard.reportes'))
            ->with(['message' => 'Reporte eliminado', 'class' => 'alert-info']);
    }

}

laravel/resources/views/dashboard/clientes/create.blade.php
@extends('layouts.dashboard')

@section('title')

    Dashobard | Clientes

@endsection

@section('clientes-view', 'active')

@section('section-title')
    <div class="page-title">
        <div class="title">Clientes</div>
        <div class="sub-title">Agregar cliente</div>
    </div>
@endsection

@section('content')

    <div class="card bg-white">
        <div class="card-header">
            Formulario de cliente
        </div>
        <div class="card-block">
            <div class="row m-a-0">
                <div class="col-lg-12">
                    <form class="form-horizontal" action="{{ route('clientes.store') }}" method="post" enctype="multipart/form-data">

                        {{ csrf_field() }}

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-4">
                                <input type="text" name="name" value="{{ old('name') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Correo electrónico</label>
                            <div class="col-sm-4">
                                <input type="text" name="email" value="{{ old('email') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Contraseña</label>
                            <div class="col-sm-4">
                                <input type="password" name="password" value="" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Empresa</label>
                            <div class="col-sm-4">
                                <input type="text" name="empresa" value="{{ old('empresa') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Telefono</label>
                            <div class="col-sm-4">
                                <input type="phone" name="telefono" value="{{ old('telefono') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Dirección</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo1" value="{{ old('campo1') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Género</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo1" value="{{ old('campo1') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 2</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo2" value="{{ old('campo2') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 3</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo3" value="{{ old('campo3') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 4</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo4" value="{{ old('campo4') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 5</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo5" value="{{ old('campo5') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 6</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo6" value="{{ old('campo6') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 7</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo7" value="{{ old('campo7') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 8</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo8" value="{{ old('campo8') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 9</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo9" value="{{ old('campo9') }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <label class="col-sm-2 control-label"></label>
                        <div class="col-sm-4">
                            <button class="m-t btn btn-primary" type="submit">Agregar</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/dashboard/clientes/edit.blade.php
@extends('layouts.dashboard')

@section('title')

    Dashobard | Clientes

@endsection

@section('clientes-view', 'active')


@section('section-title')
    <div class="page-title">
        <div class="title">Clientes</div>
        <div class="sub-title">Editar cliente</div>
    </div>
@endsection

@section('content')

    <div class="card bg-white">
        <div class="card-header">
            Formulario de cliente
        </div>
        <div class="card-block">
            <div class="row m-a-0">
                <div class="col-lg-12">
                    <form class="form-horizontal" action="{{ route('clientes.update', $cliente->id) }}" method="post" enctype="multipart/form-data">

                        {{ csrf_field() }}

                        {{ method_field('PUT') }}

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-4">
                                <input type="text" name="name" value="{{ $cliente->name }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Correo electrónico</label>
                            <div class="col-sm-4">
                                <input type="email" name="email" value="{{ $cliente->email }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        {{-- <div class="form-group">
                            <label class="col-sm-2 control-label">Contraseña</label>
                            <div class="col-sm-4">
                                <input type="password" name="password" value="" class="form-control input-rounded" required="">
                            </div>
                        </div> --}}

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Empresa</label>
                            <div class="col-sm-4">
                                <input type="text" name="empresa" value="{{$cliente->empresa }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Telefono</label>
                            <div class="col-sm-4">
                                <input type="phone" name="telefono" value="{{ $cliente->telefono }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Dirección</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo1" value="{{ $cliente->campo1 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Género</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo1" value="{{ $cliente->campo1 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 2</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo2" value="{{ $cliente->campo2 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 3</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo3" value="{{ $cliente->campo3 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 4</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo4" value="{{ $cliente->campo4 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 5</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo5" value="{{ $cliente->campo5 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 6</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo6" value="{{ $cliente->campo6 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 7</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo7" value="{{ $cliente->campo7 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 8</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo8" value="{{ $cliente->campo8 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Campo 9</label>
                            <div class="col-sm-4">
                                <input type="input" name="campo9" value="{{ $cliente->campo9 }}" class="form-control input-rounded" required="">
                            </div>
                        </div>

                        <label class="col-sm-2 control-label"></label>
                        <div class="col-sm-4">
                            <button class="m-t btn btn-primary" type="submit">Agregar</button>
                        </div>

                    </form>

                    {{-- <form action="{{ route('clientes.destroy', $cliente->id) }}" method="post">

                        {{ csrf_field() }}

                        {{ method_field('DELETE') }}

                        <button type="submit">Delete</button>

                    </form> --}}

                </div>
            </div>
        </div>
    </div>

@endsection